live_config_reload = true

# theme
import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
style = { blinking = "Always" }

[window]
dimensions = { columns = 170, lines = 25 }
padding = { x = 10, y = 10 }
decorations = "Full"
dynamic_title = true
option_as_alt = "Both"

[scrolling]
history = 0
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal =  { family = "mononoki Nerd Font", style = "Regular" }
bold = { family = "mononoki Nerd Font", style = "Bold" }
italic = { family = "mononoki Nerd Font", style = "Italic" }

[bell]
# disable visual bell
animation = "EaseOutExpo"
color = '0xffffff'
duration = 0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]
