live_config_reload = true

# theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 25 }
padding = { x = 4, y = 4 }
decorations = "Full"
dynamic_title = true
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal =  { family = "VictorMono Nerd Font", style = "Regular" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font" }

