
[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },      # skip word left
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },     # skip word right
  { key = "Backspace", mods = "Option", chars = "\u001b\u007f" }, # delete word
  { key = "Backspace", mods = "Command", chars = "\u0015" },      # delete line
  { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },    # home
  { key = "ArrowRight", mods = "Command", chars = "\u001bOF" },   # end
]
