# keybinds config
include keybinds.conf

# terminal config
scrollback_lines 5000
scrollback_pager_history_size 10
shell_integration enabled

# font config
font_size        12.0
font_family      family="BlexMono Nerd Font" wght=300 wdth=100
bold_font        family="BlexMono Nerd Font" wght=800
italic_font      postscript_name="MapleMono-NF-LightItalic"
bold_italic_font postscript_name="MapleMono-NF-BoldItalic"

# text config
copy_on_select true
text_composition_strategy legacy

# cursor config
cursor_shape beam
cursor_trail 3
cursor_trail_decay 0.1 0.4

# mouse config
mouse_hide_wait 3.0

# window config
hide_window_decorations yes
window_padding_width 4 4
initial_window_width 120c
initial_window_height 25c

# tab config
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: {title}"
active_tab_title_template "● {index}: {title}"

# layouts
enabled_layouts splits,stack

# os config
enable_audio_bell no
macos_quit_when_last_window_closed yes
macos_titlebar_color background
macos_traditional_fullscreen no
macos_show_window_title_in none
macos_option_as_alt yes

# stop paste prompt
paste_actions replace-dangerous-control-codes

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
