# keybinds config
include keybinds.conf

# terminal config
term xterm-256color
shell_integration enabled

# font config
font_size        12.0
font_family      family="BlexMono Nerd Font" wght=300 wdth=100
bold_font        family="BlexMono Nerd Font" wght=800
italic_font      postscript_name="MapleMono-NF-LightItalic"
bold_italic_font postscript_name="MapleMono-NF-BoldItalic"

# text config
copy_on_select true
text_composition_strategy legacy

# cursor config
cursor_trail 3
cursor_blink_interval 0.5 ease-in-out
cursor_shape underline
cursor_shape_unfocused unchanged

# mouse config
mouse_hide_wait 3.0

# window config
hide_window_decorations yes
window_padding_width 4 4
initial_window_width 120c
initial_window_height 25c

# tab config
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"

# layouts
enabled_layouts splits,stack

# os config
enable_audio_bell no
macos_quit_when_last_window_closed yes
macos_titlebar_color background
macos_traditional_fullscreen no
macos_show_window_title_in none
macos_option_as_alt yes

# stop paste prompt
paste_actions replace-dangerous-control-codes

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
